name: tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - uses: fabasoad/setup-prolog-action@v1
      - run: npm ci
      - run: docker compose up -d
      - run: npx wait-on http-get://localhost:1080/example.com
      - run: npm test
      - uses: mskri/check-uncommitted-changes-action@v1.0.1
        id: check-changes
      - if: steps.check-changes.outputs.changes != ''
        run: echo "There are uncommitted changes"
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - uses: fabasoad/setup-prolog-action@v1
      - run: npm ci
      - run: npm run lint
